name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Clean old build
      shell: cmd
      run: |
        if exist build rmdir /s /q build
        if exist dist rmdir /s /q dist
      continue-on-error: true
    
    - name: Build executable
      shell: cmd
      run: |
        python -m PyInstaller --clean telegram_monitor.spec
    
    - name: Find and verify executable
      id: find_exe
      shell: cmd
      run: |
        dir dist
        if exist "dist\TelegramMonitor.exe" (
          echo ::set-output name=executable_path::dist\TelegramMonitor.exe
          echo Found standalone EXE
          dir dist\TelegramMonitor.exe
        ) else if exist "dist\TelegramMonitor\TelegramMonitor.exe" (
          echo ::set-output name=executable_path::dist\TelegramMonitor\TelegramMonitor.exe
          echo Found in folder
          dir dist\TelegramMonitor
        ) else (
          echo "EXE not found in dist"
          dir dist /s
          exit 1
        )
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: TelegramMonitor-Windows
        path: ${{ steps.find_exe.outputs.executable_path }}
        retention-days: 7
    
    - name: Create GitHub release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.find_exe.outputs.executable_path }}
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

